### ISSUE TITLE
Why CUDA error

### ISSUE THREAD

**Issue by zxr111** [MIRALab-USTC/GCN4KGC#1]
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

**Comment by zq0x7a0x71** [comment]
I am sorry that I cannot reproduce errors caused by the environment. Maybe you should check the versions of nvidia driver, cuda, pytorch and dgl. Please make sure (at least) that the versions of pytorch and dgl are the same as what I list in README.

**Comment by zxr111** [comment]
&nbsp; My torch is 1.8.0 and dgl is 0.7.2 is fit your readme but still can't run



---Original---
From: "Zhanqiu ***@***.***&gt;
Date: Mon, Mar 28, 2022 23:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MIRALab-USTC/GCN4KGC] Why CUDA error (Issue #1)




 
I am sorry that I cannot reproduce errors caused by the environment. Maybe you should check the versions of nvidia driver, cuda, pytorch and dgl. Please make sure (at least) that the versions of pytorch and dgl are the same as what I list in README.

**Comment by zq0x7a0x71** [comment]
The code can run in my environment:

GPU: RTX3090
NVIDIA Driver: 465.19.01
CUDA: 11.3
cudatoolkit: 11.3.1
torch: 1.8.1+cu111
dgl-cu113: 0.7.2

Please check whether the above package versions are the same.

**Comment by wanglu1214** [comment]
> 我的 torch 是 1.8.0，dgl 是 0.7.2，符合你的自述，但仍然无法运行
> […](#)
> ---原创--- 发件人：“Zhanqiu ***@***.***> 日期：2022年3月28日 星期一 23:42 PM 实行：***@*** .***>；抄送：***@***.******@***.***>；主题：回复：[MIRALab-USTC/GCN4KGC]为什么 CUDA 错误（问题[# 1](https://github.com/MIRALab-USTC/GCN4KGC/issues/1)）很遗憾我无法更换由于环境引起的错误。也许你应该检查 nvidia 驱动程序、cuda、pytorch 和 dgl 的版本。请（至少）确保 pytorch 和 dgl 的版本与我在 README 中启动的相同。 — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此邮件是因为您创作了该主题。消息 ID：***@***.***>

你好请问你使用相同的配置后是否能够正常运行？
